# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpp < Formula
  desc "A tool for managing and synchronizing Cursor rules across multiple projects"
  homepage "https://github.com/nsnarender5511/cpp"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nsnarender5511/cpp/releases/download/v0.0.3/cpp_darwin_amd64.tar.gz"
      sha256 "7650214513d8bc6c9041b09ea1b8c204a1c9e5c1453a64fae3a6573ff016bceb"

      def install
        bin.install "cursor++"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nsnarender5511/cpp/releases/download/v0.0.3/cpp_darwin_arm64.tar.gz"
      sha256 "170736cfad6de89331aba33c5c0a3f415af20f2c9beb3f961e6dbea8603e1838"

      def install
        bin.install "cursor++"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/cpp/releases/download/v0.0.3/cpp_linux_amd64.tar.gz"
        sha256 "a53eabd3286e172a61648bfeffd9259486bed9f3056b25910c5555e2094d1460"

        def install
          bin.install "cursor++"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/cpp/releases/download/v0.0.3/cpp_linux_arm64.tar.gz"
        sha256 "f8d1eacedd340af3141dfc9519e7b9b9022f73fc81ef0192c6aa9dfc85498ba4"

        def install
          bin.install "cursor++"
        end
      end
    end
  end

  test do
    system "#{bin}/cursor++ --version"
  end
end
