# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crules < Formula
  desc "A tool for managing and synchronizing Cursor rules across multiple projects"
  homepage "https://github.com/nsnarender5511/crules"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_darwin_amd64.tar.gz"
      sha256 "7144162d4e5da5b55765c017f17e79771d1a552d4ece36aa6516caf5a318298c"

      def install
        bin.install "crules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_darwin_arm64.tar.gz"
      sha256 "7e6cf114d92175f7012a45164b7a4fef5baa51780e4c8c113e81c502bbd24826"

      def install
        bin.install "crules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_linux_amd64.tar.gz"
        sha256 "82379b089fdcd831e7c033b002d91d71790c028990ed3e7f7b1f072b6bc21131"

        def install
          bin.install "crules"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_linux_arm64.tar.gz"
        sha256 "a91751cee3fdafb23c5ecff60031196e2344209fa2b7fe5125f51d7c207e1d3d"

        def install
          bin.install "crules"
        end
      end
    end
  end

  test do
    system "#{bin}/crules --version"
  end
end
