# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crules < Formula
  desc "A tool for managing and synchronizing Cursor rules across multiple projects"
  homepage "https://github.com/nsnarender5511/crules"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_darwin_amd64.tar.gz"
      sha256 "3800181d452385bfb02a8110e59abb1412c84c61cea79e26ccd1d8b7278d077c"

      def install
        bin.install "crules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_darwin_arm64.tar.gz"
      sha256 "3fc3752aeaa036beb332f0291b4c9ff7ef296273095636bf952f1fff98f96ae7"

      def install
        bin.install "crules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_linux_amd64.tar.gz"
        sha256 "2ce718b582aba4651e8c1a64ea425d3558db4f31f45172cae2bfb20a2ce823ea"

        def install
          bin.install "crules"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.1/crules_linux_arm64.tar.gz"
        sha256 "5633224c5430da32b1a6a6c24b309726ca6196e27cb4b3abcfae5ab33e4409f9"

        def install
          bin.install "crules"
        end
      end
    end
  end

  test do
    system "#{bin}/crules --version"
  end
end
