# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crules < Formula
  desc "A tool for managing and synchronizing Cursor rules across multiple projects"
  homepage "https://github.com/nsnarender5511/crules"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.2/crules_darwin_amd64.tar.gz"
      sha256 "09b693875f7f847c32d531583b39bea8c9cd1a38edd18f785791b3fe2ae947a2"

      def install
        bin.install "crules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nsnarender5511/crules/releases/download/v0.0.2/crules_darwin_arm64.tar.gz"
      sha256 "1b8b085401d259b661c90854684831a295debbf417557aa9fcebcc4dd9304e44"

      def install
        bin.install "crules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.2/crules_linux_amd64.tar.gz"
        sha256 "86c94e5f7402cc46dff41ecff77ec7b7c0ad145b799b569e8d8764a5ac71370d"

        def install
          bin.install "crules"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nsnarender5511/crules/releases/download/v0.0.2/crules_linux_arm64.tar.gz"
        sha256 "0dc22c63e9f9b7316a644c00cc7ce9df3f8f7710e76012a025b2e07bffbf0c60"

        def install
          bin.install "crules"
        end
      end
    end
  end

  test do
    system "#{bin}/crules --version"
  end
end
